apiVersion: apps/v1
kind: Deployment
metadata:
  name: attempt-service
  labels:
    app: attempt-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attempt-service
  template:
    metadata:
      labels:
        app: attempt-service
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: attempt-service
          image: 239861161036.dkr.ecr.eu-central-1.amazonaws.com/codesnap/attempt-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-attempt-service:5432/codesnap"
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: LOGFIRE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: logfire-secrets
                  key: write-token
            - name: LOGFIRE_SERVICE_NAME
              value: "attempt-service"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
