apiVersion: v1
kind: Service
metadata:
  name: attempt-service
  labels:
    app: attempt-service
spec:
  selector:
    app: attempt-service
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP
